package pw.binom

object Versions {
    val DOCKER_API_VERSION = BuildConfig.DOCKER_API_VERSION
    val BINOM_VERSION = BuildConfig.BINOM_VERSION
    val KOTLIN_VERSION = BuildConfig.KOTLIN_VERSION
    val KOTLINX_COROUTINES_VERSION = BuildConfig.KOTLINX_COROUTINES_VERSION
}